name: Thinking Christian Beta
favicon: null
layout_spectrum: 0.5207853598985821
typography_spectrum: 0.4525345964357257
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#adb2c3'
    - '#382c29'
    - '#fefefe'
    - '#848898'
  brandStrength: 0.375
  lightness: 0.375
  saturation: 0.4036064096726477
  rhythmicContrast: 0.5
purpose: []
